# Generated by Django 3.2.23 on 2023-11-12 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dartsgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=128, verbose_name='ゲーム名')),
            ],
        ),
        migrations.CreateModel(
            name='Game_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50, verbose_name='スコア')),
                ('play_time', models.DateTimeField(blank=True, null=True, verbose_name='１ゲームにかかった時間')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartsgames.game_master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名')),
            ],
        ),
        migrations.DeleteModel(
            name='Gamemaster',
        ),
        migrations.DeleteModel(
            name='gameresult',
        ),
    ]
